# DEBUG
DEBUG_BASE_URL="http://10.0.2.2:8080"

# QA
QA_BASE_URL="https://qa.myapp.com"
QA_STORE_FILE=keystore/qa.keystore
QA_STORE_PASSWORD=123456
QA_KEY_ALIAS=qa_key
QA_KEY_PASSWORD=123456

# RELEASE
RELEASE_BASE_URL="https://api.myapp.com"
RELEASE_STORE_FILE=C:\\Users\\aymen\\.android\\keystores\\modular-release.jks
RELEASE_STORE_PASSWORD=123456
RELEASE_KEY_ALIAS=modular
RELEASE_KEY_PASSWORD=123456


# OTHERS
DEV_DB_VERSION = 1
PROD_DB_VERSION = 1
DEV_CLEAR_CACHE = true
PROD_CLEAR_CACHE = true
DEV_PIN_CERTIFICATE = "sha256/sd231sdfsdfsdf654sdfpkmsdfsdf"
RELEASE_PIN_CERTIFICATE = "sha256/sd231sdfsdfsdf654sdfpkmsdfsdfsf6efed"
DEV_MAP_KEY = "123456789"
PROD_MAP_KEY = "12345678910"